export const NAMA_SISWA = [
  "Ahmad Fauzan",
  "Aisyah Putri Ramadhani",
  "Muhammad Rizky Pratama",
  "Siti Nurhaliza",
  "Daffa Alif Maulana",
  "Nabila Aulia Rahman",
  "Fajar Nugroho",
  "Zahra Kirana Putri",
  "Rizky Aditya Saputra",
  "Aulia Rahmawati",
  "Ilham Maulana",
  "Nanda Putri Lestari",
  "Reza Ramadhan",
  "Aisyah Khadijah",
  "Bagas Pratama",
  "Nur Aini",
  "Rafi Ahmad",
  "Dina Safitri",
  "Alvin Setiawan",
  "Meylani Putri",
  "Farhan Akbar",
  "Nia Ramadhani",
  "Fikri Hidayat",
  "Putri Amalia",
  "Agus Saputra",
  "Salsa Nur Azizah",
  "Hendra Wijaya",
  "Lutfi Hakim",
  "Yuni Kartika",
  "Ardiansyah Putra",
];
